# Generated by Django 3.0.5 on 2020-04-24 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialseries',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='tutorial_slug',
            new_name='category_slug',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 9, 40, 4, 807044, tzinfo=utc)),
        ),
    ]
